src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @UniqueEntity(fields={"name"}, message="trick.name.unique")
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(
     *      message = "trick.name.notblank"
     * )
     * @Assert\Length(
     *      min = 3,
     *      max = 25,
     *      minMessage = "trick.name.min",
     *      maxMessage = "trick.name.max"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(
     *      message = "trick.content.notblank"
     * )
     * @Assert\Length(
     *      min = 3,
     *      minMessage = "trick.content.min",
     * )
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_date;

    /**
     * @ORM\OneToMany(targetEntity=Discussion::class, mappedBy="trick", orphanRemoval=true)
     */
    private $discussions;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="trick", orphanRemoval=true)
     */
    private $media;

    /**
     * @ORM\OneToOne(targetEntity=Media::class, orphanRemoval=false)
     */
    private $featured_media;

    public function __construct()
    {
        $this->discussions = new ArrayCollection();
        $this->media = new ArrayCollection();
        $this->created_date = new \DateTime();
        $this->updated_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updated_date;
    }

    public function setUpdatedDate(\DateTimeInterface $updated_date): self
    {
        $this->updated_date = $updated_date;

        return $this;
    }

    /**
     * @return Collection|Discussion[]
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function addDiscussion(Discussion $discussion): self
    {
        if (!$this->discussions->contains($discussion)) {
            $this->discussions[] = $discussion;
            $discussion->setTrick($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussion $discussion): self
    {
        if ($this->discussions->removeElement($discussion)) {
            // set the owning side to null (unless already changed)
            if ($discussion->getTrick() === $this) {
                $discussion->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedia(Media $media): self
    {
        if (!$this->media->contains($media)) {
            $this->media[] = $media;
            $media->setTrick($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        if ($this->media->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getTrick() === $this) {
                $media->setTrick(null);
            }
        }

        return $this;
    }

    public function getFeaturedMedia(): ?Media
    {
        return $this->featured_media;
    }

    public function setFeaturedMedia(?Media $featured_media): self
    {
        $this->featured_media = $featured_media;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="user.email.unique")
 * @UniqueEntity(fields={"username"}, message="user.username.unique")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(
     *      message = "user.email.notblank"
     * )
     * @Assert\NotNull(
     *      message = "user.email.notblank"
     * )
     * @Assert\Email(
     *      message = "user.email.notvalid"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     * @Assert\NotBlank(
     *      message = "user.username.notblank"
     * )
     * @Assert\Length(
     *      min = 3,
     *      max = 25,
     *      minMessage = "user.username.min",
     *      maxMessage = "user.username.max"
     * )
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture_link;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_date;

    /**
     * @ORM\OneToMany(targetEntity=Trick::class, mappedBy="user", orphanRemoval=true)
     */
    private $tricks;

    /**
     * @ORM\OneToMany(targetEntity=Discussion::class, mappedBy="user", orphanRemoval=true)
     */
    private $discussions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Assert\Length(
     *      max = 25,
     *      maxMessage = "user.firstname.max"
     * )
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Assert\Length(
     *      max = 25,
     *      maxMessage = "user.lastname.max"
     * )
     */
    private $lastname;

    public function __construct()
    {
        $this->tricks = new ArrayCollection();
        $this->discussions = new ArrayCollection();
        $this->created_date = new \DateTime();
        $this->updated_date = new \DateTime();
        $this->picture_link = "";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPictureLink(): ?string
    {
        return $this->picture_link;
    }

    public function setPictureLink(?string $picture_link): self
    {
        $this->picture_link = $picture_link;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updated_date;
    }

    public function setUpdatedDate(\DateTimeInterface $updated_date): self
    {
        $this->updated_date = $updated_date;

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setUser($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getUser() === $this) {
                $trick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Discussion[]
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function addDiscussion(Discussion $discussion): self
    {
        if (!$this->discussions->contains($discussion)) {
            $this->discussions[] = $discussion;
            $discussion->setUser($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussion $discussion): self
    {
        if ($this->discussions->removeElement($discussion)) {
            // set the owning side to null (unless already changed)
            if ($discussion->getUser() === $this) {
                $discussion->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Trick;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'trick.label.name',
                'required' => false,
            ])
            ->add('content', TextareaType::class, [
                'label' => 'trick.label.content',
                'required' => false,
            ])
            ->add('newcategory', TextType::class, [
                'label' => 'trick.label.newcategory',
                'mapped' => false,
                'required' => false
            ])
            ->add('category', EntityType::class, [
                'label' => 'trick.label.category',
                'class' => Category::class,
                'choice_label' => 'Name'
            ])
            ->add('pictures', CollectionType::class, [
                'label' => false,
                'entry_type' => FileType::class,
                'entry_options' => [
                    'label' => false,
                    'required' => false,
                ],
                'mapped' => false,
                'required' => false,
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('videolinks', CollectionType::class, [
                'label' => false,
                'entry_type' => UrlType::class,
                'entry_options' => [
                    'label' => false,
                    'required' => false,
                ],
                'mapped' => false,
                'required' => false,
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'form.save'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

templates/trick/_discussion.html.twig
<div class="container-fluid" id="discussion-area">

    {% if app.user %}
    {{ form_start(form) }}
    <div class="row justify-content-md-center">
        <div class="col-12 col-lg-8 mt-3 pt-1 border-top"></div>

        <div class="col-12 col-lg-5 form-group m-0 mt-2">
            {{ form_label(form.message, null, {'label_attr': {'class': 'sr-only'}}) }}
            {{ form_errors(form.message) }}
            {{ form_widget(form.message) }}
        </div>
        <div class="col-12 col-lg-3 mt-2">
            {{ form_widget(form.save) }}
        </div>
    </div>
    {{ form_end(form) }}
    {% endif %}

    <div class="row justify-content-md-center text-left">
        <div class="col col-lg-8 mt-3 pt-3 border-top fake-loader" id="discussions" data-fakeloader-number="10">
            {% for discussion in discussions %}
            <div class="discussion-message">
            <div class="d-flex">
                <img src="{{ asset(discussion.user.pictureLink ? upload_asset ~ discussion.user.pictureLink : 'images/no-image.png') }}" class="mr-3 imgDiscussion" alt="" />
                <p class="border flex-grow-1 p-2">
                    <span class="text-muted">
                        {{ discussion.user.username }} - {{ discussion.createdDate|date('d-m-y à H\\Hi', "Europe/Paris") }}
                        {% if is_granted('owner', discussion.user) %}
                        <a href="#" onclick="deleteMessage('{{ path('discussion_delete', {'id': discussion.id}) }}');return false;"><img src="{{ asset('images/theme/b-delete.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
                        {% endif %}
                    </span>
                    <br />{{ discussion.message }}
                </p>
            </div>
            </div>
            {% else %}
                Il n'y a pas de discussion
            {% endfor %}
        </div>
    </div>
    
</div>

templates/trick/_form.html.twig
{{ form_start(form) }}

<div class="row justify-content-center pt-3">
    <div class="col-12">
        <h1 class="mb-3 text-center">{{ 'trick.title.new'|trans }}</h1>
    </div>

    <div class="col-10 col-sm-8 col-md-7 col-lg-5 border text-center bg-light py-3 px-sm-5">
        {{ form_row(form.name) }}
        {{ form_row(form.content) }}
    </div>
</div>

<div class="row justify-content-center pt-3">
    <div class="col-12">
        <h2 class="mb-3 text-center">{{ 'trick.title.category'|trans }}</h2>
    </div>

    <div class="col-10 col-sm-8 col-md-7 col-lg-5 border text-center bg-light py-3 px-sm-5">
        {{ form_row(form.newcategory) }}
        {{ form_row(form.category) }}
    </div>
</div>

<div class="row justify-content-center pt-3">
    <div class="col-12">
        <h2 class="mb-3 text-center">{{ 'trick.title.pictures'|trans }}</h2>
    </div>

    <div class="col-10 col-sm-8 col-md-7 col-lg-5 border text-center bg-light pt-3 px-sm-5">
        <button type="button" class="add_item_link btn btn-info mb-3" data-collection-holder="{{ form.pictures.vars.id }}">{{ 'trick.button.addimage'|trans }}</button>
        {{ form_row(form.pictures, {'attr': {'class': 'form-collection'}}) }}
    </div>
</div>

<div class="row justify-content-center pt-3">
    <div class="col-12">
        <h2 class="mb-3 text-center">{{ 'trick.title.videolinks'|trans }}</h2>
        <h3 class="mb-3 text-center">{{ 'trick.title.videotype'|trans }}</h3>
    </div>

    <div class="col-10 col-sm-8 col-md-7 col-lg-5 border text-center bg-light pt-3 px-sm-5">
        <button type="button" class="add_item_link btn btn-info mb-3" data-collection-holder="{{ form.videolinks.vars.id }}">{{ 'trick.button.addlink'|trans }}</button>
        {{ form_row(form.videolinks, {'attr': {'class': 'form-collection'}}) }}
    </div>
</div>

<div class="row justify-content-center py-3">
    <div class="col-10 col-sm-8 col-md-7 col-lg-5 border text-center bg-light pt-3 px-sm-5">
        {{ form_row(form.save) }}
    </div>
</div>

{{ form_end(form) }}

templates/trick/_medias.html.twig
        
<div class="navbar-expand-lg">

    <div id="medias" class="collapse navbar-collapse">
        <div class="container-fluid p-0">
            <div class="row row-cols-1 row-cols-lg-4 row-cols-xl-6 justify-content-md-center m-2">
                {% for media in trick.media %}
                <div class="col p-1 d-flex align-items-center justify-content-center container-fluid flex-column">
                {% if media.isVideoLink %}
                    <div class="col p-0">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe width="100%" height="100%" src="{{ media.link }}" frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                {% else %}
                    <a href="#" class="col flex-grow-1 d-flex align-items-center justify-content-center px-0 image-zoom"><img src="{{ asset(upload_asset ~ media.link) }}" class="medias__img" alt=""></a>
                {% endif %}
                {% if is_granted('owner', trick.user) %}
                    <div class="d-flex justify-content-end w-100">
                        <div class="border w-60">
                            {% if not media.isVideoLink %}
                            <a href="{{ path('trick_update_featuredmedia', {'id': media.id}) }}"><img src="{{ asset('images/theme/b-edit-media.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
                            {% endif %}
                            <a href="#" onclick="deleteMessage('{{ path('media_delete', {'id': media.id}) }}');return false;"><img src="{{ asset('images/theme/b-delete.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
                        </div>
                    </div>
                {% endif %}
                </div>
                {% else %}
                    Pas de medias
                {% endfor %}
            </div>
        </div>
    </div>
    
    <a class="navbar-toggler btn btn-primary btn-lg active m-2" data-toggle="collapse" href="#medias" role="button" aria-expanded="false" aria-controls="medias">Voir les médias</a>
    
</div>

{{ include('trick/_modal.html.twig') }}

templates/trick/_modal.html.twig
<div class="modal fade" id="image-zoom" tabindex="-1" aria-labelledby="image-zoom-label" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="image-zoom-label">Agrandissement de l'image</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"><img src="" class="img-fluid" alt=""></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/trick/edit.html.twig
{% extends 'simplebase.html.twig' %}

{% block title %}{{ 'trick.title.edit'|trans }}{% endblock %}

{% block simplebase %}

<div  id="content" class="border border-bottom-0 text-center pb-5">
				
<div class="trick__header d-flex flex-column justify-content-between bg-secondary py-2" style="background-image: url({{ asset(trick.featuredMedia ? upload_asset ~ trick.featuredMedia.link : 'images/no-image.png') }});">
        
    <div class="align-self-end bg-light mr-2">
            
        <a href="{{ path('trick_show', {'slug': trick.name}) }}"><img src="{{ asset('images/theme/b-return.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
        
        <a href="{{ path('trick_remove_featuredmedia', {'id': trick.id}) }}"><img src="{{ asset('images/theme/b-remove-featuredmedia.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
        
        <a href="#" onclick="deleteMessage('{{ path('trick_delete', {'id': trick.id}) }}');return false;"><img src="{{ asset('images/theme/b-delete.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
        
    </div>
    
    <h1 class="bg-light bg-opacity text-break">{{ trick.name }}</h1>
    
    <div class="my-2 imgMenu"></div>
</div>

{{ include('trick/_medias.html.twig') }}

<div class="card text-center mx-2">
    {{ include('trick/_form.html.twig') }}
    <a class="btn btn-danger" href="#" role="button" onclick="deleteMessage('{{ path('trick_delete', {'id': trick.id}) }}');return false;">Supprimer</a>
</div>

</div>
{% endblock %}

templates/trick/new.html.twig
{% extends 'simplebase.html.twig' %}

{% block title %}Nouveau du Trick{% endblock %}

{% block simplebase %}
<div  id="content" class="border border-bottom-0 text-center pb-5">

    <div class="card text-center mx-2">
        {{ include('trick/_form.html.twig') }}
    </div>

</div>
{% endblock %}

templates/trick/show.html.twig
{% extends 'simplebase.html.twig' %}

{% block title %}Register{% endblock %}

{% block simplebase %}

<div  id="content" class="border border-bottom-0 text-center pb-5">
				
<div class="trick__header d-flex flex-column justify-content-between bg-secondary py-2" style="background-image: url({{ asset(trick.featuredMedia ? upload_asset ~ trick.featuredMedia.link : 'images/no-image.png') }});">
        
    <div class="align-self-end bg-light mr-2">
        {% if is_granted('owner', trick.user) %}
        <a href="{{ path('trick_edit', {'slug': trick.name}) }}"><img src="{{ asset('images/theme/b-edit.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
        
        <a href="#" onclick="deleteMessage('{{ path('trick_delete', {'id': trick.id}) }}');return false;"><img src="{{ asset('images/theme/b-delete.svg') }}" class="d-inline-block imgMenu m-2" alt="" /></a>
        {% endif %}
    </div>
    
    <h1 class="bg-light bg-opacity text-break">{{ trick.name }}</h1>
    
    <div class="my-2 imgMenu"></div>
</div>

{{ include('trick/_medias.html.twig') }}

<div class="card text-center mx-2">
    <div class="card-body">
        <p class="card-text text-justify text-break">{{ trick.content ? trick.content : '' }}</p>
    </div>
    <div class="card-footer text-muted">
        Auteur : {{ trick.user.lastname ? (trick.user.firstname ? trick.user.firstname ~ ' ' : '') ~ trick.user.lastname : 'inconnue' }} - 
        Catégories : {{ trick.category.name ? trick.category.name : '' }} - 
        Publié le {{ trick.createdDate ? trick.createdDate|date('d-m-y à H\\Hi', "Europe/Paris") : '' }} - 
        Mis à jour le {{ trick.updatedDate ? trick.updatedDate|date('d-m-y à H\\Hi', "Europe/Paris") : '' }}
    </div>
</div>

{{ include('trick/_discussion.html.twig') }}

</div>
{% endblock %}